name: Scheduled Pipeline

on:
  schedule:
    - cron: "*/1 * * * *"  # runs every 1 minute (testing)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron job running at $(date)"
